name: build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'imgs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'imgs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: test
        run: go test -v ./...

      - name: build binary
        run: go build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push - dev
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: loganballard/quote-msg-arm:dev
        if: github.event_name == 'pull_request'

      - name: semver bump
        id: semver_bump
        uses: zwaldowski/semver-release-action@v2
        with:
          prefix: v
          bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: Build and push - prod
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: loganballard/quote-msg-arm:prod,loganballard/quote-msg-arm:${{ steps.semver_bump.outputs.version }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'